const mongoose = require("mongoose");
const mapping = require("./model-mapping");

const UserSchema = new mongoose.Schema({
  _id: {
    // _id is the user's email
    type: String,
    required: true,
  },
  firstName: {
    // user's first name
    type: String,
    required: true,
  },
  lastName: {
    // user's last name
    type: String,
    required: true,
  },
  dateOfBirth: {
    // user's date of birth
    type: Date,
    required: true,
  },
  hash: {
    // salted hashed password
    type: String,
    required: true,
  },
  salt: {
    // random salt of generated bytes
    type: String,
    required: true,
  },
  godmode: {
    // admin rights
    type: Boolean,
    required: true,
  },
  streamKey: {
    // key for streaming
    type: String,
    required: true,
  },
  friendList: {
    // list of friends
    type: [String],
    required: false,
  },
  isStreaming: {
    type: Boolean,
    required: false,
  },

  // reset password token
  passwordToken: String,
  tokenExpiryDate: Date,
});

const User = mongoose.model(mapping.USER.model, UserSchema);
module.export = User;
